### ISSUE TITLE
Weights won't download as repo is over data quota.

### ISSUE THREAD

**Issue by a1270** [ThereforeGames/txt2mask#10]
Searching for a fix for the "_pickle.UnpicklingError: invalid load key, 'v'." i wiped the 1KiB files only to have them replace with the same files. Doing a manual git pull of the clipseg repo resulted in the following error:
`Error downloading object: weights/rd16-uni.pth (61545cd): Smudge error: Error downloading weights/rd16-uni.pth (61545cdb3a28f99d33d457c64a9721ade835a9dfbda604c459de6831c504167a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

Is there another host for these weights?

**Comment by ThereforeGames** [comment]
>Is there another host for these weights?

Yeah, I just updated the script to point to a download mirror that was mentioned in the clipseg repo. Feel free to let me know if the issue persists!
