### ISSUE TITLE
UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by Wickemu** [ThereforeGames/txt2mask#4]
When I try to use this script, this is all i get, and the prompt fails.

**Comment by ThereforeGames** [comment]
Hi @Wickemu,

This should be resolved now - for some reason Github doesn't like to download the model files in this repo, so the script will fetch them for you at runtime. Let me know if the error persists.

Thank you!

**EDIT:** After updating, you may need to delete the broken weights in `repositories\clipseg\weights` and restart the web UI to allow the script to fetch the proper files.
