### ISSUE TITLE
Inpainitng with full resolution option on have some errors

### ISSUE THREAD

**Issue by FlowDownTheRiver** [ThereforeGames/txt2mask#5]
![Screenshot 2022-09-18 at 23-05-53 Stable Diffusion](https://user-images.githubusercontent.com/71787427/190926332-5df96ba4-500c-4f01-8e78-0e37ccd6b2c2.png)
![2022-09-18 23_06_24-webui](https://user-images.githubusercontent.com/71787427/190926347-ef4f62f5-f2d3-4072-8746-ee423ad961a4.jpg)

Images tell all.but In case yoyu need to full error as written.

img2img: Emma Watson face close up smiling
Error completing request
Arguments: ('Emma Watson face close up smiling', '', 'None', 'None', None, {'image': <PIL.Image.Image image mode=RGBA size=671x1000 at 0x19A9D5816F0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=671x1000 at 0x19A9D582A40>}, None, 0, 72, 0, 13, 1, False, False, 1, 1, 1, 7.5, 0.4, -1.0, -1.0, 0, 0, 0, 512, 512, 0, 0, 64, True, 0, 8, '', '', '', '', 1, 50, 0, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 4, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, None, '', False, 'face', 96, '<div class="gr-block gr-box relative w-full overflow-hidden border-solid border border-gray-200 gr-panel"><p>If you like my work, please consider showing your support on <strong><a href="https://patreon.com/thereforegames" target="_blank">Patreon</a></strong>. Thank you! &#10084;</p></div>', 1, '', 4, '', True) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\ui.py", line 134, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui\webui.py", line 55, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui\modules\img2img.py", line 131, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stable-diffusion-webui\modules\scripts.py", line 159, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui\scripts\txt2mask.py", line 104, in run
    processed = processing.process_images(p)
  File "C:\stable-diffusion-webui\modules\processing.py", line 263, in process_images
    p.init(seed=all_seeds[0])
  File "C:\stable-diffusion-webui\modules\processing.py", line 440, in init
    image_masked.paste(image.convert("RGBA").convert("RGBa"), mask=ImageOps.invert(self.mask_for_overlay.convert('L')))
  File "C:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1628, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match

**Comment by FlowDownTheRiver** [comment]
![01034-3561474788-Emma Watson face close up](https://user-images.githubusercontent.com/71787427/190926433-9a63844a-5a7a-4cc4-9c6e-3d6133474a6e.jpg) 
without full resolution option, it works but it redraws the image at a given resolution completes the masked area.

**Comment by ThereforeGames** [comment]
Hi [FlowDownTheRiver](https://github.com/FlowDownTheRiver), I just pushed an update that should allow the script to work with inpainting at full resolution. Thanks!

**Comment by FlowDownTheRiver** [comment]
Thank you so much! This is a life saver.I really apreciate your work.
