### ISSUE TITLE
[Feature Request] Output the mask image along with the generated image in the UI

### ISSUE THREAD

**Issue by GuiAworld** [ThereforeGames/txt2mask#7]
Output the mask image along with the generated image on the Output UI, that way you can preview the mask, and use the generated mask with another script by simply dragging the outputted mask to the Input Mask area

**Comment by ThereforeGames** [comment]
Great idea! Added:

![image](https://user-images.githubusercontent.com/95403634/191090921-50cd029a-0c8d-439c-aae4-af70bb56fa64.png)

Eventually, I would like to have the option of sending the mask directly to the "upload a mask" box, but I need to do more research to see how custom scripts can interact with the rest of Automatic's UI.
