### ISSUE TITLE
Way to change maximum input tokens? 

### ISSUE THREAD

**Issue by Delcos** [ThereforeGames/txt2mask#8]
Is there a config to change the max accepted prompts?  Thanks.

**Comment by ThereforeGames** [comment]
Hi Delcos,

I'm not sure if this is exactly what you were asking, but I just pushed an update that lets you specify multiple masking prompts with `|` as a delimiter.

For example, if you enter `a hand|a face|a flower` each of these three items will be processed by clipseg independently, and the final mask will be assembled by stacking the submasks on top of each other.

**Comment by Delcos** [comment]
> Owner

That's a pretty cool update, should be fun to try it out. I was meaning is there a way to extend the limit of tokens you enter, for example if I entered 20 words, it will process all of them, but if I enter 21, in the output txt file it will say it culled the last one because there were too many. I'm wondering if there's a way to change that limit.
